name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  esp-elf-gcc:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/esp-elf-gcc.yml@v0.1.0
    with:
      path: examples/esp32
      target: esp32

  x86_64-linux-gnu-gcc:
    uses: ZIMO-Elektronik/.github-workflows/.github/workflows/x86_64-linux-gnu-gcc.yml@v0.1.0
